import { EligibilityRule } from '../types';

export const ELIGIBILITY_RULES: EligibilityRule[] = [
  // Cancer Screening
  {
    id: 'mammogram',
    name: 'Mammography',
    gender: 'FEMALE',
    ageMin: 50,
    ageMax: 74,
    domain: 'cancer',
    nudge: 'Patient is due for biennial breast cancer screening. Consider ordering mammography.',
  },
  {
    id: 'cervical',
    name: 'Cervical Cancer Screening',
    gender: 'FEMALE',
    ageMin: 21,
    ageMax: 65,
    domain: 'cancer',
    nudge: 'Cervical cancer screening is recommended (Pap smear every 3 years or Pap + HPV co-test every 5 years).',
  },
  {
    id: 'prostate',
    name: 'Prostate Screening (PSA)',
    gender: 'MALE',
    ageMin: 50,
    ageMax: 75,
    domain: 'cancer',
    nudge: 'Prostate cancer screening (PSA/DRE) is recommended. Consider shared decision-making with patient.',
  },
  {
    id: 'colorectal',
    name: 'Colorectal Screening',
    gender: 'BOTH',
    ageMin: 45,
    ageMax: 75,
    domain: 'cancer',
    nudge: 'Colorectal cancer screening is due. Consider ordering colonoscopy, FIT test, or Cologuard.',
  },
  // Vaccines
  {
    id: 'flu',
    name: 'Influenza Vaccine',
    gender: 'BOTH',
    ageMin: 6,
    ageMax: 120,
    domain: 'vaccines',
    nudge: 'Annual influenza vaccination is recommended. Consider administering today or scheduling.',
  },
  {
    id: 'pneumococcal',
    name: 'Pneumococcal Vaccine',
    gender: 'BOTH',
    ageMin: 65,
    ageMax: 120,
    domain: 'vaccines',
    nudge: 'Pneumococcal vaccination (PCV20 or PPSV23) recommended for adults 65+. Review immunization status.',
  },
  {
    id: 'tdap',
    name: 'Tdap / Tetanus Booster',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'vaccines',
    nudge: 'Tdap booster is recommended if not received in the past 10 years. Consider administering today.',
  },
  {
    id: 'rsv',
    name: 'RSV Vaccine',
    gender: 'BOTH',
    ageMin: 60,
    ageMax: 120,
    domain: 'vaccines',
    nudge: 'RSV vaccine (Arexvy or Abrysvo) is recommended for adults 60+. Discuss with patient.',
  },
  // Cardiovascular
  {
    id: 'bp',
    name: 'Blood Pressure Control',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'cardiovascular',
    nudge: 'Blood pressure measurement and management should be documented. Ensure BP is within goal.',
  },
  {
    id: 'lipid',
    name: 'Lipid Panel',
    gender: 'BOTH',
    ageMin: 40,
    ageMax: 75,
    domain: 'cardiovascular',
    nudge: 'Lipid panel is recommended for cardiovascular risk assessment. Consider ordering today.',
  },
  // Diabetes Management
  {
    id: 'a1c',
    name: 'A1C Testing',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 75,
    domain: 'diabetes',
    nudge: 'A1C should be checked at least annually for diabetic patients. Consider ordering today.',
  },
  {
    id: 'eye_exam',
    name: 'Diabetic Eye Exam',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'diabetes',
    nudge: 'Annual diabetic eye exam is overdue. Refer to optometry or ophthalmology.',
  },
  {
    id: 'foot_exam',
    name: 'Diabetic Foot Exam',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'diabetes',
    nudge: 'Annual diabetic foot exam recommended. Perform monofilament test and peripheral pulse check.',
  },
  {
    id: 'microalbumin',
    name: 'Microalbumin / Kidney Check',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'diabetes',
    nudge: 'Urine microalbumin or ACR should be checked annually for diabetic patients. Consider ordering.',
  },
  // Other Preventive
  {
    id: 'dexa',
    name: 'Bone Density (DEXA)',
    gender: 'BOTH',
    ageMin: 50,
    ageMax: 120,
    domain: 'other',
    nudge: 'Bone density screening (DEXA) is recommended. Consider ordering to screen for osteoporosis.',
  },
  {
    id: 'depression',
    name: 'Depression Screening',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'other',
    nudge: 'Annual depression screening (PHQ-9) is recommended. Consider administering today.',
  },
  {
    id: 'wellness',
    name: 'Annual Wellness Visit',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'other',
    nudge: 'Annual Wellness Visit (AWV) should be completed. Review health maintenance checklist.',
  },
  {
    id: 'bmi',
    name: 'BMI / Weight Counseling',
    gender: 'BOTH',
    ageMin: 18,
    ageMax: 120,
    domain: 'other',
    nudge: 'BMI assessment and weight counseling should be documented. Consider nutritional referral if indicated.',
  },
];
